# Generated by Django 5.2.1 on 2025-09-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
