# Generated by Django 5.2.1 on 2025-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0007_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='unique_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
